apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata: 
  name: catalog-hpa
spec:
  maxReplicas: 3
  minReplicas: 1
  scaleTargetRef: 
    apiVersion: v1
    kind: Deployment
    name: catalog-deployment
  targetCPUUtilizationPercentage: 50
